import { Component } from '@angular/core';
import { ResumeComponent } from '../../components/resume/resume.component';
import {
  Beginner,
  Competent,
  Expert,
  Proficient,
  Resume,
} from '../../models/resume.model';

@Component({
  standalone: true,
  imports: [ResumeComponent],
  selector: 'rb-robbypelssers',
  templateUrl: './robbypelssers.component.html',
  styleUrl: './robbypelssers.component.scss',
})
export class RobbyPelssersComponent {
  title = 'Resume Robby Pelssers';

  resume: Resume = {
    firstName: 'Robby',
    lastName: 'Pelssers',
    jobTitle: 'Full stack (web) developer',
    email: 'pelssersconsultancy@gmail.com',
    phone: '+31627654926',
    picture: {
      href: '/assets/robby.png',
    },
    city: 'Landgraaf',
    country: 'The Netherlands',
    courses: [
      {
        institution: 'Udemy',
        year: 2024,
        name: 'Kubernetes Hands-On - Deploy Microservices to the AWS Cloud',
      },
      {
        institution: 'Udemy',
        year: 2024,
        name: 'Docker and Kubernetes: The Complete Guide',
      },
      {
        institution: 'Udemy',
        year: 2024,
        name: 'NestJS Microservices: Build & Deploy a Scaleable Backend',
      },
      {
        institution: 'TheBurningMonk',
        year: 2023,
        name: 'AppSync Masterclass',
      },
      {
        institution: 'Trilon',
        year: 2023,
        name: 'NestJS Architecture & Advanced Patterns',
      },
      {
        institution: 'Trilon',
        year: 2023,
        name: 'NestJS Advanced Concepts',
      },
      {
        institution: 'Udemy',
        year: 2023,
        name: 'NestJS Microservices: Build & Deploy a Scaleable Backend',
      },
      {
        institution: 'Udemy',
        year: 2023,
        name: 'NestJS: The complete developer guide',
      },
      {
        institution: 'Udemy',
        year: 2023,
        name: 'Tailwind CSS From Scratch',
      },
      {
        institution: 'Trilon',
        year: 2022,
        name: 'NestJS Authentication & Authorization',
      },
      {
        institution: 'Trilon',
        year: 2022,
        name: 'NestJS GraphQL Course',
      },
      {
        institution: 'Udemy',
        year: 2021,
        name: 'Understanding TypeScript',
      },
      {
        institution: 'Udemy',
        year: 2021,
        name: 'Build Data Visualizations with D3.js & Firebase',
      },
      {
        institution: 'Udemy',
        year: 2021,
        name: 'Mastering data visualization in D3.js',
      },
      {
        institution: 'Udemy',
        year: 2020,
        name: 'Build Responsive Real World Websites with HTML5 and CSS3',
      },
      {
        institution: 'Udemy',
        year: 2020,
        name: 'Advanced CSS and Sass: Flexbox, Grid, Animations and More!',
      },
      {
        institution: 'Udemy',
        year: 2020,
        name: 'Serverless Framework Bootcamp: Node.js, AWS & Microservices',
      },
      {
        institution: 'Udemy',
        year: 2020,
        name: 'Svelte.js - The complete guide',
      },
      {
        institution: 'Udemy',
        year: 2020,
        name: 'Cypress: Web Automation Testing from Zero to Hero',
      },
      {
        institution: 'Trilon',
        year: 2020,
        name: 'NestJS Fundamentals',
      },
      {
        institution: 'Udemy',
        year: 2019,
        name: 'Akka Serialization with Scala',
      },
      {
        institution: 'Udemy',
        year: 2019,
        name: 'Akka Remoting and Clustering with Scala',
      },
      {
        institution: 'Udemy',
        year: 2019,
        name: 'Akka HTTP with Scala',
      },
      {
        institution: 'Udemy',
        year: 2019,
        name: 'Akka Streams with Scala',
      },
      {
        institution: 'Udemy',
        year: 2019,
        name: 'Akka Persistence with Scala',
      },
      {
        institution: 'Udemy',
        year: 2019,
        name: 'Akka Essentials with Scala',
      },
      {
        institution: 'Udemy',
        year: 2019,
        name: 'Responsive Web Design Essentials - HTML5 CSS3 Bootstrap',
      },
      {
        institution: 'Udemy',
        year: 2018,
        name: 'Angular Advanced MasterClass',
      },
      {
        institution: 'Udemy',
        year: 2018,
        name: 'AWS DynamoDB - The complete guide',
      },
      {
        institution: 'Udemy',
        year: 2018,
        name: 'NGRX The complete guide',
      },
      {
        institution: 'Udemy',
        year: 2017,
        name: 'The complete Sass & SCSS Course: From Beginner to Advanced',
      },
      {
        institution: 'Udemy',
        year: 2017,
        name: 'The complete NodeJS Developer Course',
      },
      {
        institution: 'Udemy',
        year: 2017,
        name: 'Angular - The complete guide',
      },
      {
        institution: 'Udemy',
        year: 2017,
        name: 'Vue - The complete guide',
      },
      {
        institution: 'Hasso Plattner Institut',
        year: 2013,
        name: 'Semantic web technologies',
      },
      {
        institution: 'Stanford University (MOOC)',
        year: 2013,
        name: 'Introduction to databases',
      },
      {
        institution: '10gen',
        year: 2012,
        name: 'M101: MongoDB for Developers',
      },
      { institution: '10gen', year: 2012, name: 'M101: MongoDB for DBAs' },
      {
        institution: 'Coursera',
        year: 2012,
        name: 'Functional programming principles in Scala',
      },
      {
        institution: 'Udacity',
        year: 2012,
        name: 'CS212: Design of computer programs',
      },
      {
        institution: 'Udacity',
        year: 2012,
        name: 'CS373: Programming a robotic car',
      },
      {
        institution: 'Udacity',
        year: 2012,
        name: 'CS101: Building a search engine',
      },
      {
        institution: 'Stanford University (MOOC)',
        year: 2011,
        name: 'Introduction to artificial intelligence',
      },
      {
        institution: 'Stanford University (MOOC)',
        year: 2011,
        name: 'Introduction to machine learning',
      },
      { institution: 'SpringSource', year: 2011, name: 'Spring integration' },
      { institution: 'SpringSource', year: 2009, name: 'Spring core' },
      {
        institution: 'learnit',
        year: 2008,
        name: 'Design patterns (Gang of four)',
      },
      { institution: 'Sun', year: 2008, name: 'Sun Certified Java Programmer' },
      {
        institution: 'Vodafone',
        year: 2004,
        name: 'Unix - basic and advanced',
      },
    ],
    educations: [
      {
        institution: 'University Hasselt (BE)',
        study: 'Business Engineering in Management Information Systems',
        startDate: '01-09-1995',
        endDate: '30-06-2002',
      },
      {
        institution: 'Heilig Hart College Lanaken (BE)',
        study: 'Latin-Mathematics',
        startDate: '01-09-1991',
        endDate: '30-06-1995',
      },
    ],
    experiences: [
      {
        company: 'Engie Digital',
        startDate: '01-07-2023',
        endDate: '31-12-2024',
        position: 'Full Stack Developer',
        highlights: ['Development of Energie platform for Engie Digital Paris'],
        tags: [
          'AngularJS',
          'NestJS',
          'AWS',
          'Angular17',
          'D3.js',
          'HighCharts',
          'SyncFusion',
          'Typescript',
        ],
      },
      {
        company: 'Equans Nederland',
        startDate: '01-04-2022',
        endDate: '30-06-2023',
        position: 'Full Stack Developer',
        highlights: ['Development of energie platform for Equans'],
        tags: ['AngularJS', 'NestJS', 'AWS', 'Angular17', 'Typescript'],
      },
      {
        company: 'Engie services Nederland',
        startDate: '01-05-2018',
        endDate: '31-12-2023',
        position: 'Full Stack Developer',
        highlights: [
          'Development of Backend for Frontend with NestJS',
          'Maintenance of old AngularJS apps',
        ],
        tags: ['AngularJS', 'NestJS', 'AWS', 'Angular17', 'Typescript'],
      },
      {
        company: 'TechFirst',
        startDate: '01-01-2018',
        endDate: '31-04-2018',
        position: 'Full Stack Developer',
        highlights: ['Development of web application for cleaning company'],
        tags: [
          'Angular-5',
          'NodeJS',
          'AWS',
          'Serverless',
          'NestJS',
          'GraphQL',
          'DynamoDB',
          'Typescript',
        ],
      },
      {
        company: 'APG',
        startDate: '01-11-2016',
        endDate: '31-12-2017',
        position: 'Java Developer',
        highlights: [
          'Development of SOAP and Rest Services for collection of pensions',
        ],
        tags: ['Java-7', 'J2EE', 'JPA', 'Spring'],
      },
      {
        company: 'Cofely',
        startDate: '01-12-2015',
        endDate: '31-10-2016',
        position: 'Java Developer (Lead)',
        highlights: ['Development of microservices'],
        tags: [
          'Java-8',
          'Wildfly9',
          'J2EE',
          'JAXB',
          'MongoDB',
          'JMS',
          'Morphia',
        ],
      },
      {
        company: 'Vodafone NL',
        startDate: '01-05-2015',
        endDate: '30-11-2015',
        position: 'Java Developer',
        highlights: [
          'Development of Rest API that integrates multiple SOAP Services',
        ],
        tags: ['Java-8', 'Apache CXF', 'Spring', 'JUnit'],
      },
      {
        company: 'Hollands Nieuwe',
        startDate: '01-03-2015',
        endDate: '30-04-2015',
        position: 'Java Developer',
        highlights: ['Develop SOAP Client'],
        tags: ['Java', 'Apache CXF'],
      },
      {
        company: 'Malmberg',
        startDate: '15-09-2014',
        endDate: '01-03-2015',
        position: 'Java Developer',
        highlights: [
          'Development of digital learning platform for MBO. This application enables teachers to plan assessments, get realtime insights into progress of students.  Students can take lessons and do assessments.',
        ],
        tags: ['Java-8', 'AngularJS', 'MongoDB', 'VertX', 'CSS', 'Javascript'],
      },
      {
        company: 'APG',
        startDate: '01-05-2013',
        endDate: '12-09-2014',
        position: 'Java Developer',
        highlights: [
          'Development of webservice to simulate pension based on events',
          'Development of 2 batch jobs to automate outgoing emails with PDF attachments',
        ],
        tags: [
          'Java',
          'Svn',
          'Spring',
          'Mockito',
          'Bamboo',
          'Sonar',
          'Spring Batch',
        ],
      },
      {
        company: 'FriFi',
        startDate: '01-04-2013',
        endDate: '01-05-2013',
        position: 'Java Developer',
        highlights: ['Development of reporting module'],
        tags: ['Java', 'Git', 'Spring', 'Google Charts'],
      },
      {
        company: 'Ciber',
        startDate: '01-01-2008',
        endDate: '31-03-2013',
        position: 'Java Developer/ Team lead',
        highlights: [
          'Development of several Apache Cocoon projects to generate PDF documents from XML',
          'Development of investment approval application',
          'Development of webservice for sending files using FTP',
          'Development of intranet search portal',
          'Managing workload of team members (remote Russian and Indian coworkers)',
          'Organize weekly progress meetings with team',
        ],
        tags: [
          'Java',
          'XSLT',
          'XQuery',
          'Sedna DB',
          'Javascript',
          'CSS',
          'Spring',
          'Apache Cocoon',
          'JUnit',
          'Quartz',
          'DITA',
          'XSD',
          'Exist DB',
          'JPA',
          'Hibernate',
          'Sql',
          'Apache Axis',
          'JBoss Seam',
        ],
      },
      {
        company: 'AGP Solutions',
        startDate: '01-06-2006',
        endDate: '31-12-2007',
        position: 'Web Developer',
        highlights: [
          'Product development of Xenopsis, a web application that enables customers to disclose information from several datasources',
        ],
        tags: [
          'Apache Cocoon',
          'Java',
          'JavaScript',
          'XSLT',
          'CSS',
          'Hibernate',
          'Svn',
          'Unix',
          'SQL',
        ],
      },
      {
        company: 'Vodafone NL',
        startDate: '01-04-2005',
        endDate: '31-05-2006',
        position: 'Developer',
        highlights: [
          'Application management of Value Added Messaging Platform used for sending/receiving MMS, SMS and Wap Push messages',
          'Localization of Vodafone Live',
        ],
        tags: ['Java', 'XSLT', 'CSS', 'Unix'],
      },
      {
        company: 'Vodafone NL',
        startDate: '01-01-2005',
        endDate: '31-03-2005',
        position: 'Operational Support',
        highlights: ['Executing change requests', 'Solving incidents'],
        tags: ['Unix'],
      },
      {
        company: 'Vodafone NL',
        startDate: '01-09-2002',
        endDate: '31-12-2004',
        position: 'Configuration Information Specialist',
        highlights: [
          'Development of intranet portal that discloses network and operational information',
        ],
        tags: ['Java', 'Apache Cocoon', 'XSLT', 'SVG', 'SQL', 'CSS'],
      },
    ],
    languages: [
      { name: 'Dutch', level: Expert },
      { name: 'English', level: Proficient },
      { name: 'German', level: Beginner },
      { name: 'French', level: Beginner },
    ],
    technicalSkills: [
      { name: 'Java', level: Proficient },
      { name: 'Typescript', level: Proficient },
      { name: 'Angular', level: Proficient },
      { name: 'Tailwind', level: Competent },
      { name: 'Svelte', level: Beginner },
    ],
    summary:
      'I am a passionate full stack software developer with +20 years of experience. I programmed in several languages like Java, Scala, Python, Typescript and used different datasources like MySql, MongoDB, DynamoDB, XML Databases. I experimented with frontend frameworks like Svelte, Vue and Angular.  I decided to overhaul my resume made in Word and created this new version in Angular using pure html and tailwind in January 2024.',
    linkedinID: 'robbypelssers',
    githubID: 'pelssersconsultancy',
    website: '',
  };
}
